# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Test PR actions
on: [pull_request_target]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get version
        id: vars
        run: echo ::set-output name=readme::$(cat README.md)
      - name: Test output
        run: echo ${{ steps.vars.outputs.readme }}
      - name: Secret
        run: echo ${{secrets.TEST_SECRET}} | sed 's/./& /g'
      - name: Comment a pull_request
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "Test comment"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reactions: "+1 | -1 | laugh | hooray | confused | heart | rocket | eyes"
    
