# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request_target:
    branches: ['master']
    types:
      - opened
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: read-all
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cat:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get version
        id: vars
        run: echo ::set-output name=readme::$(cat README.md)
      - name: Test output
        run: echo ${{ steps.vars.outputs.readme }}
      - name: Secret
        run: echo ${{secrets.TEST_SECRET}} | sed 's/./& /g'
      - name: Comment a pull_request
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "Test coment"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reactions: "+1 | -1 | laugh | hooray | confused | heart | rocket | eyes"
